blank_issues_enabled: false
contact_links:
 - name: Getting Help on IPFS
   url: https://ipfs.tech/help
   about: All information about how and where to get help on IPFS.
 - name: Helia Wiki
   url: https://github.com/ipfs/helia/wiki
   about: Documentation, FAQ, and Manifesto for Helia.
 - name: Helia Examples
   url: https://github.com/ipfs-examples/helia-examples
   about: Code examples for using Helia.
 - name: IPFS Official Discussion Forum
   url: https://discuss.ipfs.tech
   about: Please post general questions, support requests, and discussions here.
